# Generated by Django 4.2.2 on 2023-11-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedagem',
            name='valor',
            field=models.FloatField(verbose_name='Valor da hospedagem'),
        ),
    ]
